spring:
    datasource:
        username: root
        password: jiwon0126

        jpa:
            hibernate:
                ddl-auto: create
                dialect: org.hibernate.dialect.MySQLDialect
            show-sql: true
